# Before running, create .env file & place the environment variables inside the file
version: '3'
networks:
  dem:
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - dem

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8000:80"
    depends_on:
      - postgres
    networks:
      - dem

  weather_app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_KEY: ${API_KEY}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5001:${PORT}"
    depends_on:
      - postgres
    networks:
      - dem